version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:jessie-curl-browsers
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Download terraform
          command: wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
      - run:
          name: unzip terraform
          command: unzip terraform_0.11.5_linux_amd64.zip
      - run :
          name: cd base && ls -al
          command: cd base && ls -al
      - run:
          name: terraform retrieve state from S3
          command: cd base && ../terraform remote config -backend=S3 -backend-config="bucket=$BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=eu-west-2"
      - run:
          name: terraform plan
          command: cd base && ../terraform plan -out=terraform.plan -input=false
      - run:
          name: view plan
          command: cd base && cat terraform.plan


